language: php

services:
  - docker

before_install:
  - docker-compose --version
  - docker-compose build --pull
  - docker-compose up --build -d
  - docker ps -a

before_script:
  - docker-compose exec dev docker-as-drupal bootstrap --with-default-content --with-elasticsearch

script:
  - docker-compose exec test docker-as-drupal behat --with-elasticsearch
