services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.25.5

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose build --pull
  - docker-compose up --build -d
  # wait on Docker to be ready, especially MariaDB that takes many seconds to be up.
  - sleep 30
  - docker-compose exec dev docker-as-drupal bootstrap --with-default-content --with-elasticsearch

script:
  - docker-compose exec test docker-as-drupal behat --with-elasticsearch
