version: '3.6'

services:
  # Drupal development server
  dev:
    build: .
    command: docker-as-wait --mysql -- docker-as-drupal apache-server
    depends_on:
      - db
      - mail
      - elasticsearch
    environment:
      DATABASE_URL: mysql://drupal:drupal@db/drupal_development
      SMTP_HOST: mail:1025
      PRIVATE_FILES: /var/www/web/sites/default/files/private
      DEFAULT_CONTENT: gos_default_content
      DRUPAL_CONFIG_SET: >-
        elasticsearch_helper.settings elasticsearch_helper.host elasticsearch
    restart: "no"
    volumes:
      - backups:/var/backups
      # Drupal
      - ./composer.json:/var/www/composer.json:cached
      - ./composer.lock:/var/www/composer.lock:cached
      - ./config:/var/www/config:cached
      - ./web/modules/custom:/var/www/web/modules/custom:cached
      # Files
      - ./web/sites/default/files:/var/www/web/sites/default/files:delegated

  # Drupal test server
  test:
    build: .
    command: docker-as-wait --mysql -- docker-as-drupal apache-server
    depends_on:
      - browser
      - db
      - mail
      - elasticsearch
    environment:
      DATABASE_URL: mysql://drupal:drupal@db/drupal_test
      SMTP_HOST: mail:1025
      PRIVATE_FILES: /var/www/web/sites/default/files/private
      DEFAULT_CONTENT: gos_default_content
      REQUIRED_DIRECTORIES: >-
        /var/www/log/behat
        /var/www/dump/behat
      DRUPAL_CONFIG_SET: >-
        elasticsearch_helper.settings elasticsearch_helper.host elasticsearch
      BEHAT_PROFILE: default
      TEST_DISABLE_MODULES: big_pipe
    restart: "no"
    volumes:
      - backups:/var/backups
      # Drupal
      - ./composer.json:/var/www/composer.json:cached
      - ./composer.lock:/var/www/composer.lock:cached
      - ./config:/var/www/config:cached
      - ./web/modules/custom:/var/www/web/modules/custom:cached
      # Behat
      - ./behat:/var/www/behat:cached
      - ./behat.yml:/var/www/behat.yml:cached
    networks:
      default:
        aliases:
          # Hosts used in default content for testing
          - api.gos.test

  # Test browser
  browser:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm

  # Database
  db:
    image: mariadb:10.1
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal\_%
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - database:/var/lib/mysql

  # Mail
  mail:
    image: schickling/mailcatcher
    restart: always

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.5
    restart: always
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./config/elasticsearch/analysis:/usr/share/elasticsearch/config/analysis
#     - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  # Elasticsearch browser
  dejavu:
    image: appbaseio/dejavu:3.2.3
    depends_on:
      - elasticsearch
    ports:
      - '1358:1358'
    links:
      - elasticsearch

volumes:
  database:
  backups:
  esdata:
    driver: local
