version: '3.6'

services:
  # Drupal development server
  app:
    hostname: app
    ports:
      - "8080:80"

  # Drupal test server
  test:
    hostname: test
    ports:
      - "8888:8888"

  # Database
  db:
    ports:
      - "3306:3306"

  # Elasticsearch
  elasticsearch:
    ports:
      - "9200:9200"
