services:
  # Drupal development server
  app:
    hostname: app
    ports:
      - "8080:80"
#    build:
#      args:
#        - 'NEW_RELIC_AGENT_VERSION=9.18.1.303'
#        - 'NEW_RELIC_LICENSE_KEY=LICENSE'
#        - 'NEW_RELIC_APPNAME=Games of Switzerland - Local'
#        - 'NEW_RELIC_DAEMON_ADDRESS=newrelic-apm-daemon:31339'
#    depends_on:
#      - newrelic-apm-daemon

  # Drupal test server
  test:
    hostname: test
    ports:
      - "8888:80"

  # Mail
  mailcatcher:
    ports:
      - "1080:1080"

  # Database
  db:
    ports:
      - "13306:3306"

  # Mail
  mail:
    ports:
      - "1080:1080"

  # Elasticsearch
  elasticsearch:
    ports:
      - "9200:9200"
    volumes:
      - ./config/elasticsearch/analysis:/usr/share/elasticsearch/config/analysis

  # Elasticsearch browser
  # dejavu:
  #   image: appbaseio/dejavu:latest
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - '1358:1358'
  #   links:
  #     - elasticsearch
