version: '3.8'

services:

  # Drupal app server
  app:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: ./docker/startup.sh
    depends_on:
      - db
      - mailcatcher
      - elasticsearch
    environment:
      APP_ENV: development
      BASE_URL: http://localhost
      DATABASE_URL: mysql://drupal:drupal@db/drupal_development
      DEFAULT_CONTENT: gos_default_content
    restart: unless-stopped
    volumes:
      - backups:/var/backups
      - ./patches:/var/www/patches
      # Drupal
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./config:/var/www/config
      - ./web/modules/custom:/var/www/web/modules/custom
      - ./web/sites/default/settings.development.php:/var/www/web/sites/default/settings.development.php
      # Files
      - ./web/sites/default/files:/var/www/web/sites/default/files:delegated
      # Drush
      - ./web/sites/default/drush.development.yml:/var/www/drush/drush.yml
      # Gin
      - ./web/sites/default/files/gin-custom.css:/var/www/web/sites/default/files/gin-custom.css
      # Behat
      - ./behat:/var/www/behat
      - ./behat.yml:/var/www/behat.yml

  # Drupal test server
  test:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: ./docker/startup.sh
    depends_on:
      - browser
      - db
      - mailcatcher
      - elasticsearch
    environment:
      APP_ENV: test
      BASE_URL: http://localhost
      DATABASE_URL: mysql://drupal:drupal@db/drupal_test
      DEFAULT_CONTENT: gos_default_content
      BEHAT_PROFILE: default
      TEST_DISABLE_MODULES: big_pipe
    restart: unless-stopped
    volumes:
      - backups:/var/backups
      - ./patches:/var/www/patches
      # Drupal
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./config:/var/www/config
      - ./web/modules/custom:/var/www/web/modules/custom
      # Behat
      - ./behat:/var/www/behat
      - ./behat.yml:/var/www/behat.yml
      - ./phpunit.xml.dist:/var/www/phpunit.xml.dist
      # Drush
      - ./web/sites/default/drush.development.yml:/var/www/drush/drush.yml
    networks:
      default:
        aliases:
          # Hosts used in default content for testing
          - api.gos.test

  newrelic-apm-daemon:
    image: newrelic/php-daemon:9.13.0

  # Test browser
  browser:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm

  # Database
  db:
    image: mariadb:10.4
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal_%
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql

  # Mailcatcher
  mailcatcher:
    image: schickling/mailcatcher
    restart: unless-stopped

  # Elasticsearch
  elasticsearch:
    build:
      dockerfile: docker/Dockerfile.elasticsearch
      context: .
    restart: unless-stopped
    environment:
      - node.name=gos-es01
      - cluster.initial_master_nodes=gos-es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  database:
  backups:
  esdata:
    driver: local
