<?php

/**
 * @file
 * Primary module hooks for Game module for Games of Switzerland.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\gos_game\CompletenessCalculator;
use Drupal\gos_game\ReleasesCompiler;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function gos_game_node_presave(EntityInterface $entity) {
  if ($entity->bundle() === 'game') {
    /** @var \Drupal\node\NodeInterface $game */
    $game = $entity;

    // Calculate the completeness score field value.
    $score = CompletenessCalculator::calculation($game);

    // Save field calculations.
    $game->set('field_completeness', $score);

    // Get Game compiled release years field value.
    $years = ReleasesCompiler::compileYears($game);
    $game->set('field_release_years', $years);

    // Get Game compiled platforms field value.
    $platforms = ReleasesCompiler::compilePlatforms($game);
    $game->set('field_release_platforms', array_keys($platforms));
  }
}
