FROM elasticsearch:8.7.1

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu && \
    /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-phonetic

COPY ./config/elasticsearch/analysis /usr/share/elasticsearch/config/analysis
