_core:
  default_config_hash: FGYrMvt5Li0Jm92wyoGSiFFNoI_WqcHTeNDMq4jHId0
status: true
mapping:
  type: simple
  conditions:
    not:
      extensions:
        - css
        - js
  domain: api.swissgames.garden
scheme: 'https://'
farfuture:
  status: true
stream_wrappers:
  - public
