module:
  new_relic_rpm: -20
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  bamboo_twig: 0
  bamboo_twig_loader: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  consumer_image_styles: 0
  consumers: 0
  contact: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_group: 0
  field_ui: 0
  fieldable_path: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  focal_point: 0
  gos_elasticsearch: 0
  gos_game: 0
  gos_rest: 0
  gos_site: 0
  help: 0
  history: 0
  image: 0
  image_effects: 0
  jsonapi: 0
  jsonapi_extras: 0
  link: 0
  media: 0
  media_library: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  rabbit_hole: 0
  rdf: 0
  rest: 0
  restui: 0
  serialization: 0
  simple_sitemap: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ef_fieldset: 0
  views_ui: 0
  webp: 0
  menu_link_content: 1
  pathauto: 1
  elasticsearch_helper: 10
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  gos: 0
  gos_admin: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
