_core:
  default_config_hash: OhypfKr4_Eo8XwXg3Sios05lN-LjxOhSdSOSkEN9Ndo
logo:
  use_default: true
brand_image:
  use_default: true
  use_custom_wallpaper_folder: 1
  custom_wallpaper_folder_path: sites/default/gin-wallpapers
