_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: e85e1685-b207-4ca4-987d-43b3619f58ab
name: 'Games of Switzerland'
mail: dev@swissgames.garden
slogan: ''
page:
  403: ''
  404: ''
  front: /user/login
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
