_core:
  default_config_hash: oE_T7Du8mMCGKYgI_9c_8IuU9G8sx19FvC8UshASX6k
enabled_entity_types:
  node: {  }
  path_alias: {  }
  menu_link_content: {  }
auto_purge:
  enabled: false
  after: '30 days'
compact_overview: false
