<?php

/**
 * @file
 * Contains gos_migrate.module.
 */

/**
 * Implements hook_migration_plugins_alter().
 */
function gos_migrate_migration_plugins_alter(array &$definitions): void {
  $module_path = Drupal::service('extension.path.resolver')->getPath('module', 'gos_migrate');

  foreach (array_keys($definitions) as $migration_plugin_id) {
    if (mb_strpos($migration_plugin_id, 'gos_') !== 0) {
      continue;
    }

    if (!isset($definitions[$migration_plugin_id]['source'], $definitions[$migration_plugin_id]['source']['plugin'], $definitions[$migration_plugin_id]['source']['path'])) {
      continue;
    }

    if (is_file($definitions[$migration_plugin_id]['source']['path'])) {
      continue;
    }

    $path = $module_path . $definitions[$migration_plugin_id]['source']['path'];

    if (!is_file($path)) {
      continue;
    }

    $definitions[$migration_plugin_id]['source']['path'] = $path;
  }
}
